version: '3'

networks: 
  my_stack_network:
    driver: bridge
    ipam:
      driver: default

services:
  api:
    build: .
    networks:
      - my_stack_network
    ports:
      - "3333:80"
    environment:
      PORT: 80